language: node_js
node_js:
  - "8"
script: yarn run build
deploy:
  provider: s3
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  bucket: www.hidden.computer
  region: us-east-2
  skip_cleanup: true
  acl: public_read
  local_dir: build
  on:
    branch: master
env:
  global:
  - secure: I6DsZXP0qAYeDcBgVesazU9JyB9l9urE64E7UxUI+y7I//APLm32wkqVyUN+/Gkb5ElF8Yc0DXcrZSiU3pMBcLFSiSlwP+Py9ptigECNQ7PH2qqlEnR+V9/7L5Iga4r7yUXYfBoa2YvQgl4fdLrp/5tp1kZxBr9Cac/GSjR3gyA9ZpJURePC+mLADPEwpuxUEB+eHfSuRVw03Li1B3aKCWro4tPlNJ5yb7TAdthcRhJfREjl6mk4b41/6sysVoeU4UB6Rdgp0q5AkT2k64JAwSl/jVxhZJJpEvDw1MfDkgHJm3XDGeugQptARwPAAxv2zUuHn7MCA49IoSnToa35DPi4j0EMeoG4omNA8LQZ5siRt3vTSvVrkdqn4zyZkpIJr0RPzt63YL/1N0/k6gYy0oivI/JksGh1Olh9xIkErO+lCOznq6Khu2cKM8h+CXCvEVU2z2M4zfwpaVstr8ZnH/1LnIo1uB+GeyNttT1nvNJOp1dYjlYlIwX6awCE3CvpHMYXz62dDHtlOog47eFtdabVp+chsBP41hc6o2iVJqwOTP4CVsidup01xhGwgA7urJauMDkBcjWWTg6vY9VPAlm6jDHYiRZsnAR8/btX117UwMOq6pB8CyJjcr1FtyPrrTdIs9SuJpTKKJP8/m+qIbhiii1Xj+9jNecGs10zga4=
  - secure: h/TzCXMWKGe6xxFhfqVy7eAH77fiWzNCWcwNNFU1g3BK8rycB66jJbWVeiboNSg4doX1brfJmkihHpEYNjSZny8veDbY8VlK9aUceeSh7aXEDc2erkJuobztD0D6SWnu920tN5Oa+IMgvCOJAGd0dSNjOdkSZjr8r940PjJ6Y2cst4LGn1WPCcUFSjYBvdFQTQO3oGH54DU5zyyXSfOk23ML9IOiy8ZOtwK27sJmSxIjWHrlCSQjvc4J6sVlcYuPQmgATc5z1ujhZIU+zjqOMP96E3NuQ+WnmN9B15gciQVB8zaWB+X4iDKKGxbhfCnLN305dBcsWJ97wtsbedSMxbkeB3d043wPBe0AqJBeNuG7+By7mfU/ruZ798Aiy55eWh5fDWM3aAzJkAmwVulZjQ2H/MZsIQLOeQtCL5HUW/f4n5/4vpq1MNps20WhHzjyoq8tGBLRNUdU39DIINq5vxmUK5/l666qiCxr9nM3v2DDC48gPR9kTHW4nvEhdSghJGWSLw9+KLCDQinWsWGwL19xQksaLS0+zcMFMfbcvFLAx5TxRdBmTbJtnXmviaLlXaXbq5H7r/fBixnTjFSHbq4Hj8NcFvOEO3f/GcVDsSA4JpQ3/trBOmxPHZBamgeWIUN/sjqnSpK9GZhZjHuxrXGghuha0RGLHoWdlLqsXlw=
