version: 0.2

env:
  variables:
    APP_NAME: "hidden"
    SERVICE_NAME: "www"

phases:
  install:
    commands:
      - apt-add-repository ppa:duggan/jo --yes
      - apt-get update
      - apt-get install -y jo jq
      - npm i
  pre_build:
    commands:
      - ServiceEnv=$(echo $CODEBUILD_INITIATOR | sed 's/^.*@@@//')
      - >
        UtilityBucket=$(aws cloudformation list-exports | \
          jq -c --arg searchValue $APP_NAME:ApplicationUtilityBucketName \
          '.[] | .[] | select(contains({Name: $searchValue})) | .Value' | \
          sed 's/"//g')
      - >
        StaticOutputBucket=$(aws cloudformation list-exports | \
          jq -c --arg searchValue $APP_NAME:$SERVICE_NAME:$ServiceEnv:StaticOutputBucketResourceName \
          '.[] | .[] | select(contains({Name: $searchValue})) | .Value' | \
          sed 's/"//g')
      - >
        StaticOutputBucketDomainName=$(aws cloudformation list-exports | \
          jq -c --arg searchValue $APP_NAME:$SERVICE_NAME:$ServiceEnv:StaticOutputBucketDomainName \
          '.[] | .[] | select(contains({Name: $searchValue})) | .Value' | \
          sed 's/"//g')
      - >
        AwsRegion=$(aws cloudformation list-exports | \
          jq -c --arg searchValue $APP_NAME:AwsRegion \
          '.[] | .[] | select(contains({Name: $searchValue})) | .Value' | \
          sed 's/"//g')
      - >
        AppTld=$(aws cloudformation list-exports | \
          jq -c --arg searchValue $APP_NAME:AppTld \
          '.[] | .[] | select(contains({Name: $searchValue})) | .Value' | \
          sed 's/"//g')
      - >
        AppHostedZoneId=$(aws cloudformation list-exports | \
          jq -c --arg searchValue $APP_NAME:$SERVICE_NAME:$ServiceEnv:AppHostedZoneId \
          '.[] | .[] | select(contains({Name: $searchValue})) | .Value' | \
          sed 's/"//g')

  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo pushing infra templates to s3
      - >
          aws s3 cp
          --recursive
          --exclude *.swp
          infra/www/service
          s3://$UtilityBucket/$SERVICE_NAME/$ServiceEnv/service-infra
      - echo generating template config
      - jo Parameters=$(jo AwsRegion=$AwsRegion ServiceName=$SERVICE_NAME OriginBucket=$StaticOutputBucket OriginDomain=$StaticOutputBucketDomainName UtilityBucket=$UtilityBucket ServiceEnv=$ServiceEnv AppHostedZoneId=$AppHostedZoneId AppName=$APP_NAME AppTld=$AppTld) > TemplateConfig.json
artifacts:
  secondary-artifacts:
    cloudfronttemplate:
      files:
        - TemplateConfig.json
        - infra/www/service/Service.yaml
      discard-paths: yes
    staticassets:
      files:
        - '**/*'
      discard-paths: no
      base-directory: build

