AWSTemplateFormatVersion: 2010-09-09

Parameters:
  OriginBucket:
    Type: String
  OriginDomain:
    Type: String
  AppName:
    Type: String
  ServiceName:
    Type: String
  ServiceEnv:
    Type: String
  AppTld:
    Type: String

Conditions:
  IsProd: !Equals [!Ref ServiceEnv, master]

Resources:
  Distribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - Fn::If:
              - IsProd
              - !Sub '${AppName}.${AppTld}'
              - !Ref AWS::NoValue
          - Fn::If:
              - IsProd
              - !Sub '${ServiceName}.${AppName}.${AppTld}'
              - !Ref AWS::NoValue
          - Fn::If:
              - IsProd
              - !Ref AWS::NoValue
              - !Sub '${ServiceEnv}.${ServiceName}.${AppName}.${AppTld}'
        DefaultCacheBehavior:
          AllowedMethods:
            - 'GET'
            - 'HEAD'
          CachedMethods:
            - 'GET'
            - 'HEAD'
          Compress: true
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: 'none'
            Headers:
              - 'Origin'
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 86400
          TargetOriginId: !Ref OriginBucket
          ViewerProtocolPolicy: 'allow-all'
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: 'http1.1'
        IPV6Enabled: false
        Origins:
          - DomainName: !Ref OriginDomain
            Id: !Ref OriginBucket
            OriginPath: ''
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CfOriginAccessIdentity}'
        PriceClass: 'PriceClass_All'

  CfOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Identity of the www.hidden.computer cloudfront distribution'

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref OriginBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: 'Allow'
            Principal:
              CanonicalUser: !GetAtt CfOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub 'arn:aws:s3:::${OriginBucket}/*'

Outputs:
  DomainName:
    Value: !GetAtt Distribution.DomainName

