AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AppHostedZoneId:
    Type: String
  CloudFrontDomainName:
    Type: String
  ServiceName:
    Type: String
  AppName:
    Type: String
  AppTld:
    Type: String
  ServiceEnv:
    Type: String

Conditions:
  IsProd: !Equals [!Ref ServiceEnv, master]

Resources:
  WwwAlias:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2 # This is the canonical cloudfront hosted zone ID
      HostedZoneId: !Ref AppHostedZoneId
      Name:
        Fn::If:
          - IsProd
          - !Sub '${ServiceName}.${AppName}.${AppTld}'
          - !Sub '${ServiceEnv}.${ServiceName}.${AppName}.${AppTld}'
      Type: A

  DefaultServiceAlias:
    Type: AWS::Route53::RecordSet
    Condition: IsProd
    Properties:
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2 # This is the canonical cloudfront hosted zone ID
      HostedZoneId: !Ref AppHostedZoneId
      Name: !Sub '${AppName}.${AppTld}'
      Type: A

